### DISCUSSION TITLE
How to ensure tooltip stays in browser visible area?

### DISCUSSION THREAD

**Discussion by NashL** [ReactTooltip/react-tooltip#1133] [Q&A] [answered]
I realized that when the text I want to display inside the tooltip is too long and there are no breaklines inside the text (`\n`), the tooltip container runs off the page, I would like to make the tooltip container take on the maximum width as possible without leaving the viewport

**Comment by gabrieljablonski** [comment, marked as answer]
Try something like this

```css
.react-tooltip {
  max-width: calc(100vw - 54px);
  word-break: break-all;
}
```

You might want to play around with the `word-break` attribute, but the `max-width` should be good.

By my calculations, it should actually be 42px, since there's an internal padding of 16px on each side, plus a 5px minimum margin from the page border, but for some reason that's not enough.

**Reply by gabrieljablonski** [reply]
Figured it out, it's because there was a scrollbar when I was testing, 42px is indeed the correct number. Here's a suggestion on how to deal with a scrollbar

```css
body {
  --scrollbar-width: calc(100vw - 100%);
}

.react-tooltip {
  max-width: calc(100vw - 42px - var(--scrollbar-width));
  word-break: break-all;
}
```

This assumes that the html body is the element on your application that has the scrollbar. You might have to adjust that.
