### ISSUE TITLE
Is there a way to customize where the triangle pointer is positioned?

### ISSUE THREAD

**Issue by milesmeow** [ReactTooltip/react-tooltip#438]
Ex:
For tooltips that show up at place='top', can I move the the triangle pointer to the bottom left of the tooltip and still have the triangle point to the appropriate item that triggered the tooltip?

For tooltips that show top or bottom, maybe there could be an attribute to position the triangle left, middle or right.

For tooltips that show left or right, maybe there could be an attribute to top, middle, bottom

**Comment by aronhelser** [comment]
No, there is no way to do that right now. I would be happy to look at a PR with that feature, though!

**Comment by RonnyO** [comment]
I needed this and a proper PR requires more time, but meanwhile I tweaked placement in my (S)CSS. Something like:

```scss
$tooltip-offset: 167px;
.my-tooltip {
    width: 403px;
    height: 212px;
    padding: 12px 10px;
    margin-top: 26px;
    margin-left: $popover-offset;
}

.__react_component_tooltip.place-bottom {
    $tip-offset: -$tooltip-offset - 8px;
    &::before {
        margin-left: $tip-offset;
    }

    &::after {
        margin-left: $tip-offset + 2px;
    }
}
```
