### ISSUE TITLE
Transform transitions

### ISSUE THREAD

**Issue by andrewoh531** [ReactTooltip/react-tooltip#525]
I'm trying to add a `transition: transform` to `react-tooltip` but getting weird behaviour. I am wondering if this transition is compatible with `react-tooltip` or whether it conflicts with the position calculation.

The behaviour I'm getting is the tooltip will show in the correct position, and then somewhere completely off from the target element it's meant to show next to. It will alternative between those two positions fairly consistently.

I've added a custom classname to my `react-tooltip` which looks like:
```css

.react-tooltip--animations {
  transition: transform 0.3s ease-in-out !important;
}

.react-tooltip--animations.show {
  transform: translateY(0);
}
```
