### ISSUE TITLE
Warning: Prop `dangerouslySetInnerHTML` did not match.

### ISSUE THREAD

**Issue by audn** [ReactTooltip/react-tooltip#675]
Hey!

This code,

```jsx
   <ReactTooltip
      effect="solid"
      place="bottom"
      delayShow={200}
      arrowColor="transparent"
      backgroundColor="#1d2c3e"
      id="newApp"
   >
      <h1 className="text-sm text-white font-medium">Upload</h1>
   </ReactTooltip>
``` 

Seems to be giving me this:
![image](https://user-images.githubusercontent.com/21041399/108627331-4db9da80-7455-11eb-9c8d-46b3ce6608b2.png)

I've tried to use `<p>` tags instead of `<h1>` and so on, but I can't seem to get rid of it.
I do indeed have custom CSS on it, and it looks like this:

```css
.__react_component_tooltip {
  border-radius: 5px !important;
  border: 1px solid #273552 !important;
  background: #404f6d !important;
  padding: 10px 15px !important;
  color: #b7c4dc !important;
  z-index: 100 !important;
}
```
