### ISSUE TITLE
How to add a border to arrow

### ISSUE THREAD

**Issue by sawa060** [ReactTooltip/react-tooltip#998]
How can I add a border to arrow?

The arrow is just a rotated squares, so if I simply do a border, it will look like this.
<img width="203" alt="スクリーンショット 2023-04-02 22 08 55" src="https://user-images.githubusercontent.com/51919128/229533004-5433ed1a-c5f4-40a4-8a8f-5cada0695f97.png">

Even if I use border-bottom, border-left, border-top and border-right, if the place changes, it will look like this
<img width="385" alt="スクリーンショット 2023-04-03 23 15 20" src="https://user-images.githubusercontent.com/51919128/229536357-2870a6a9-7665-4dc7-80b9-ffd0584c231d.png">

I want to display the border like this.
<img width="356" alt="スクリーンショット 2023-04-02 22 10 56" src="https://user-images.githubusercontent.com/51919128/229533103-b1e49cc0-eeec-46f1-8ea4-a45c393bb7d0.png">

Is there any way to do this? Or do you plan to take any action in the future?

**Comment by gabrieljablonski** [comment]
You can take advantage of the classes we use to indicate the tooltip positioning. Take a look at the `styles.css` file on [this example](https://stackblitz.com/edit/react-ts-8rzrqo?file=App.tsx,style.css).

Here's one way to do it:

```css
.react-tooltip {
  background-color: cyan;
  color: black;
  border: 1px solid black;
}

.react-tooltip__place-top > .react-tooltip-arrow {
  border-bottom: 1px solid black;
  border-right: 1px solid black;
}

.react-tooltip__place-right > .react-tooltip-arrow {
  border-bottom: 1px solid black;
  border-left: 1px solid black;
}

.react-tooltip__place-bottom > .react-tooltip-arrow {
  border-top: 1px solid black;
  border-left: 1px solid black;
}

.react-tooltip__place-left > .react-tooltip-arrow {
  border-top: 1px solid black;
  border-right: 1px solid black;
}
```

As of right now, we're not planning on doing anything that would allow you to do this without custom CSS.
Though this is probably a good example to add to the documentation, so thanks for the suggestion!
